# Generated by Django 5.1.6 on 2025-03-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes_diarios', '0002_alter_cortesdiarios_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortesdiarios',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
