# Generated by Django 5.1.6 on 2025-03-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes_diarios', '0003_cortesdiarios_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cortesdiarios',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
