# Generated by Django 5.1.6 on 2025-03-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes_diarios', '0004_alter_cortesdiarios_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cortesdiarios',
            name='efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cortesdiarios',
            name='tarjeta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cortesdiarios',
            name='transferencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
