# Generated by Django 5.1.6 on 2025-03-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cortes_diarios', '0005_alter_cortesdiarios_efectivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cortesdiarios',
            name='efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cortesdiarios',
            name='tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cortesdiarios',
            name='transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
