# Generated by Django 5.1.6 on 2025-03-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cortes_diarios', '0006_alter_cortesdiarios_efectivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortesdiarios',
            name='gastos',
        ),
    ]
