# Generated by Django 5.1.4 on 2025-02-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], default='cliente', max_length=10, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sexo',
            field=models.IntegerField(blank=True, choices=[(1, 'Hombre'), (2, 'Mujer')], null=True, verbose_name='Sexo'),
        ),
    ]
