# Generated by Django 5.1.4 on 2025-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_customuser_options_customuser_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(choices=[('admin', 'Administrador'), ('chofer', 'Chofer'), ('cliente', 'Cliente')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('chofer', 'Chofer'), ('cliente', 'Cliente')], default='cliente', max_length=10, verbose_name='Rol'),
        ),
    ]
