# Generated by Django 5.1.4 on 2025-02-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_customuser_nombre_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
