# Generated by Django 5.1.6 on 2025-02-14 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_type_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_person',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.type_person'),
        ),
    ]
