# Generated by Django 5.1.6 on 2025-02-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_type_person_user_id_customuser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
